SELECT NOME FROM TB_CLIENTES

SELECT LOWER(NOME) FROM TB_CLIENTES

SELECT UPPER(NOME) FROM TB_CLIENTES

SELECT INITCAP(NOME) FROM TB_CLIENTES 

SELECT ENDERECO1, BAIRRO FROM TB_CLIENTES

SELECT CONCAT(CONCAT(ENDERECO1, ', '), BAIRRO) FROM TB_CLIENTES

SELECT ENDERECO1 || ', ' || BAIRRO || ' - ' || ESTADO FROM TB_CLIENTES

SELECT NOME, LPAD(NOME, 30, '*') FROM TB_PRODUTOS

SELECT NOME, RPAD(NOME, 30, '*') FROM TB_PRODUTOS

SELECT NOME, SUBSTR(NOME,3,6) FROM TB_PRODUTOS

SELECT NOME, INSTR(NOME, 'Teixeira') FROM TB_CLIENTES

SELECT NOME FROM TB_CLIENTES WHERE INSTR(NOME, 'Teixeira') <> 0;

SELECT NOME FROM TB_CLIENTES WHERE INSTR(NOME, 'Mattos') <> 0;

SELECT ' Joao ' AS X, LTRIM(' Joao ') FROM DUAL;

SELECT ' Joao ' AS X, TRIM(' Joao ') FROM DUAL;

SELECT ' Joao ' AS X, RTRIM(' Joao ') FROM DUAL;