-- João Pedro Giaretta RA: 23008717
-- Filipe Daniel Medeiros RA: 23002322
-- Inicie criando uma tabela ALUNOS com os campos (CODIGO(SEQUENCE), NOME, RA). 
-- Em seguida uma outra tabela chamada DICIPLINAS com os dados (CODIGO(SEQUENCE), NOME, QTD_HORAS_AULAS) 
-- Em seguida uma tabela chamada MATRICULAS (que vincula um aluno numa disciplina) CODIGO(SEQUENCE), ALUNO(FK), DISCIPLINA(FK), FREQUENCIA(EM PORCENTAGEM)
-- POR ULTIMO UMA TABELA CHAMADA FREQUENCIAS COM OS CAMPOS CODIGO(SEQUENCE), MATRICULA(FK) E DATA

CREATE TABLE ALUNOS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(500) NOT NULL,
    RA VARCHAR2(500) NOT NULL UNIQUE
);

CREATE SEQUENCE SEQ_ALUNOS START WITH 1 INCREMENT BY 1;

CREATE TABLE DISCIPLINAS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(500) NOT NULL,
    QTD_HORAS_AULAS NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_DISCIPLINAS START WITH 1 INCREMENT BY 1;

CREATE TABLE MATRICULAS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    ALUNO INTEGER NOT NULL,
    DISCIPLINA INTEGER NOT NULL,
    FREQUENCIA NUMBER DEFAULT 0,
    
    CONSTRAINT FK_ALUNO FOREIGN KEY(ALUNO)
    REFERENCES ALUNOS(CODIGO),
    CONSTRAINT FK_DISCIPLINA FOREIGN KEY(DISCIPLINA)
    REFERENCES DISCIPLINAS(CODIGO)
);

CREATE SEQUENCE SEQ_MATRICULAS START WITH 1 INCREMENT BY 1;

CREATE TABLE FREQUENCIAS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    MATRICULA INTEGER NOT NULL,
    DATA DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_MATRICULA FOREIGN KEY(MATRICULA)
    REFERENCES MATRICULAS(CODIGO)
);

CREATE SEQUENCE SEQ_FREQUENCIAS START WITH 1 INCREMENT BY 1;

-- TRIGGER, TODA VEZ QUE INSERIR OU EXCLUIR UM REGISTRO NA TABELA FREQUENCIAS DEVE SER ATUALIZADA A FREQUENCIA DAQUELE ALUNO NA MATRICULA

CREATE OR REPLACE TRIGGER TRG_ATUALIZA_FREQUENCIA
AFTER INSERT OR DELETE ON FREQUENCIAS
FOR EACH ROW
DECLARE 
    total_frequencia NUMBER;
    codigo_disciplina INTEGER;
    qnt_horas NUMBER;
    porcentagem_frequencia NUMBER;
BEGIN 
    SELECT COUNT(*) INTO total_frequencia FROM FREQUENCIAS WHERE MATRICULA = :NEW.MATRICULA OR MATRICULA = :OLD.MATRICULA;

    SELECT DISCIPLINA INTO codigo_disciplina FROM MATRICULAS WHERE CODIGO = :NEW.CODIGO;

    SELECT QTD_HORAS_AULAS INTO qnt_horas FROM DISCIPLINAS WHERE CODIGO = codigo_disciplina;

    porcentagem_frequencia := (total_frequencia / qnt_horas) * 100;
    
    UPDATE MATRICULAS
    SET FREQUENCIA = porcentagem_frequencia
    WHERE CODIGO = :NEW.CODIGO;
END;



