ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-mm-dd';

drop table assentos;

drop sequence SEQ_ASSENTOS

CREATE TABLE ASSENTOS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    CONDICAO CHAR(1) DEFAULT '0',
    AERONAVE INTEGER NOT NULL,
    
    CONSTRAINT CK_CONDICAO_1_OU_0 CHECK (CONDICAO IN ('1','0')),
    CONSTRAINT FK_ASSENTOS_AERONAVE FOREIGN KEY(AERONAVE)
    REFERENCES AERONAVES(CODIGO)
);

CREATE SEQUENCE SEQ_ASSENTOS START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SEQ_ASSENTOS;

DROP TABLE ASSENTOS

CREATE SEQUENCE SEQ_AERONAVES START WITH 1 INCREMENT BY 1;

INSERT INTO AERONA

select SEQ_AERONAVES.CURRVAL from dual

INSERT INTO ASSENTOS
(CODIGO, AERONAVE)
VALUES
(SEQ_ASSENTOS.NEXTVAL, SEQ_AERONAVES.CURRVAL);

select * from voos

INSERT INTO VOOS
(CODIGO, DATA_VOO, HR_CHEGADA, HR_SAIDA, VALOR, TRECHO)
VALUES
(222, TO_DATE('2023-08-09', 'yyyy-mm-dd'), TO_DATE('10:00:00', 'hh24:mi:ss'),  
TO_DATE('11:00:00', 'hh24:mi:ss'), 150, 23)

commit;

select * from voos