DROP SEQUENCE SEQ_EX_LANCAMENTOS;
DROP SEQUENCE SEQ_EX_CONTAS;

DROP TABLE EX_LANCAMENTOS;
DROP TABLE EX_CONTAS;

CREATE TABLE EX_CONTAS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    NOME VARCHAR2(500) NOT NULL,
    DATA_ABERTURA DATE DEFAULT SYSDATE,
    DATA_ENCERRAMENTO DATE,
    SALDO NUMBER(11,2) DEFAULT 0
);

CREATE TABLE EX_LANCAMENTOS(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    DATA DATE DEFAULT SYSDATE,
    DESCRICAO VARCHAR2(100) NOT NULL,
    VALOR NUMBER(11,2) NOT NULL,
    CONTA INTEGER NOT NULL,
    CONSTRAINT FK_LANCAMENTO_CONTA
    FOREIGN KEY (CONTA)
    REFERENCES EX_CONTAS(CODIGO),
    
    CONSTRAINT CK_VALOR_DIFERENTE_ZERO
    CHECK(VALOR != 0)
);

CREATE SEQUENCE SEQ_EX_CONTAS START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EX_LANCAMENTOS START WITH 1 INCREMENT BY 1;

INSERT INTO EX_CONTAS
(CODIGO, CPF, NOME)
VALUES
(SEQ_EX_CONTAS.NEXTVAL, 11111111111, 'Manoel Albino');

INSERT INTO EX_CONTAS
(CODIGO, CPF, NOME)
VALUES
(SEQ_EX_CONTAS.NEXTVAL, 22222222222, 'Manoela Tagliatti');

COMMIT;

CREATE OR REPLACE TRIGGER TRG_ATUALIZA_SALDO_CONTA
AFTER INSERT ON EX_LANCAMENTOS
FOR EACH ROW
DECLARE
    v_valor_lancamento NUMBER;
BEGIN

    -- OBTER O VALOR DO LANCAMENTO.
    v_valor_lancamento := :NEW.VALOR;
    
    -- ATUALIZA O SALDO DA CONTA
    UPDATE EX_CONTAS
    SET SALDO = (SALDO + v_valor_lancamento)
    WHERE CODIGO = :NEW.CONTA;
    
END;

-- INSERINDO LANCAMENTOS
INSERT INTO EX_LANCAMENTOS
(CODIGO, DESCRICAO, VALOR, CONTA)
VALUES
(SEQ_EX_LANCAMENTOS.NEXTVAL, 'Deposito em dinheiro', 1000, 10000);

INSERT INTO EX_LANCAMENTOS
(CODIGO, DESCRICAO, VALOR, CONTA)
VALUES
(SEQ_EX_LANCAMENTOS.NEXTVAL, 'Saque', -100, 10000);

INSERT INTO EX_LANCAMENTOS
(CODIGO, DESCRICAO, VALOR, CONTA)
VALUES
(SEQ_EX_LANCAMENTOS.NEXTVAL, 'Recebimento de PIX', 500, 10000);

SELECT * FROM EX_CONTAS;
SELECT * FROM EX_LANCAMENTOS;

-- PROCEDURE: QUANDO FAZEMOS UM PROGRAMA EM PL/SQL, ELE PODE APENAS SER UM BLOCO ANONIMO COMPOSTO DE DECLARE, BEGIN E END.
-- NOS PODEMOS TRANSFORMAR ESTE PROGRAMA QUE CONSTRUIMOS NUM PROGRAMA ARMAZENADO NO ORACLE, O NOME DISSO É STORADE PROCEDURE.
-- ENTÃO, UMA STOREDE PROCEDURE É UM PROGRAMA EM LINGUAGEM PL/SQL QUE PODEMOS USAR QUANDO QUISERMOS, BASTA CHAMA-LO.

CREATE OR REPLACE PROCEDURE TRANSFERIR_VALORES_ENTRE_CONTAS(
    in_valor NUMBER, in_conta_origem INTEGER, in_conta_destino INTEGER
)
IS
    saldo_conta_origem NUMBER;
    valor_a_descontar NUMBER;
BEGIN

    -- obter o saldo da conta origem e guardar na variavel de saldo_conta_origem
    SELECT SALDO INTO saldo_conta_origem
    FROM EX_CONTAS WHERE CODIGO = in_conta_origem;
    
    IF saldo_conta_origem >= in_valor THEN
        
        valor_a_descontar := (in_valor * -1)
        
        INSERT INTO LANCAMENTOS
        (CODIGO, DESCRICAP, VALOR, CONTA)
        VALUES
        (SEQ_EX_LANCAMENTOS.NEXTVAL, 'Transferencia para conta: ', 